repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
      -   id: check-added-large-files
      -   id: check-ast
      -   id: check-case-conflict
      -   id: check-json
      -   id: check-yaml
      -   id: check-toml
      -   id: check-symlinks
      -   id: check-merge-conflict
      -   id: check-executables-have-shebangs
      -   id: check-shebang-scripts-are-executable
      -   id: fix-byte-order-marker
      -   id: no-commit-to-branch
      -   id: forbid-new-submodules
      -   id: debug-statements
      -   id: mixed-line-ending
      -   id: trailing-whitespace
      -   id: pretty-format-json
          args:
            - "--autofix"
            - "--indent=2"
            - "--no-sort-keys"

  - repo: local
    hooks:
    - id: poetry-check
      name: poetry check
      types: ["python"]
      language: system
      entry: poetry check
      pass_filenames: false

    - id: absolufy-imports
      name: absolufy-imports
      types: ["python"]
      language: system
      entry: poetry run absolufy-imports --never

    - id: isort
      name: isort
      types: ["python"]
      language: system
      entry: poetry run isort

    - id: black
      name: black
      types: ["python"]
      language: system
      entry: poetry run black

    - id: flake8
      name: flake8
      types: ["python"]
      language: system
      entry: poetry run flake8

    - id: mypy
      name: mypy
      types: ["python"]
      language: system
      entry: poetry run mypy

    - id: pylint
      name: pylint
      types: ["python"]
      language: system
      entry: poetry run pylint
      exclude: ^sample_project/snippets/migrations
      args: ["-rn", "-sn"]
