[tool.poetry]
name = "drf-vcr"
version = "0.1.0"
description = ""
authors = ["Xavier Francisco <xavier.n.francisco@gmail.com>"]
readme = "README.md"
packages = [{include = "drf_vcr"}]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.3"
djangorestframework = "^3.14.0"


[tool.poetry.group.sample_project.dependencies]
pygments = "^2.13.0"
drf-spectacular = "^0.24.2"
django = "^4.1.3"
djangorestframework = "^3.14.0"
django-extensions = "^3.2.1"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-django = "^4.5.2"
mypy = "^0.991"
django-stubs = "^1.13.0"
djangorestframework-stubs = "^1.8.0"
types-pygments = "^2.13.1.1"
pylint = "^2.15.7"
pylint-django = "^2.5.3"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "sample_project.settings"
django_find_project = false
pythonpath = ["sample_project"]
python_files = ["tests.py", "test_*.py", "*_tests.py"]

[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black"

[tool.pylint.format]
max-line-length = "88"

[tool.mypy]
strict = true
disallow_subclassing_any = false
plugins = [
  "mypy_django_plugin.main",
  "mypy_drf_plugin.main",
]

[tool.pylint.master]
load-plugins = "pylint_django"
django-settings-module="sample_project.sample_project.settings"
ignore = """
  migrations
"""

[tool.pylint.messages_control]
enable = "useless-suppression"
disable = """
  missing-function-docstring,
  missing-module-docstring,
  missing-class-docstring,
  unsubscriptable-object,
  useless-super-delegation
"""

[tool.pylint.similarities]
min-similarity-lines=10
ignore-imports=true
ignore-comments=false
ignore-docstrings=false
ignore-signatures=false

[tool.pylint.design]
max-parents=12
max-attributes=12
min-public-methods=0

[tool.django-stubs]
django_settings_module = "sample_project.sample_project.settings"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
