# Generated by Django 4.1.3 on 2022-11-29 16:21

from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def forward(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    User = apps.get_model("auth", "User")
    User.objects.create(
        username="red",
        password=make_password("password"),
        is_superuser=True,
        is_active=True,
    )
    User.objects.create(
        username="green",
        password=make_password("password"),
        is_superuser=False,
        is_active=True,
    )
    User.objects.create(
        username="blue",
        password=make_password("password"),
        is_superuser=False,
        is_active=False,
    )


def reverse(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    User = apps.get_model("auth", "User")
    User.objects.filter(username__in=["red", "green", "blue"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
