# Generated by Django 4.1.3 on 2022-11-29 16:22

from textwrap import dedent

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def forward(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    User = apps.get_model("auth", "User")
    Snippet = apps.get_model("snippets", "Snippet")

    red = User.objects.filter(username="red").first()
    Snippet.objects.create(
        title="r1",
        linenos=True,
        language="python",
        owner=red,
        code=dedent(
            """
            def forward(apps, schema_editor):
                User = apps.get_model("auth", "User")
            """
        ),
    )

    green = User.objects.filter(username="green").first()
    Snippet.objects.create(
        title="g1",
        linenos=True,
        language="python",
        owner=green,
        code=dedent(
            """
            def reverse(apps, schema_editor):
                Snippet = apps.get_model("snippets", "Snippet")
            """
        ),
    )
    Snippet.objects.create(
        title="g2",
        linenos=False,
        language="c",
        owner=green,
        code=r'm(r,g,b){printf("#%06x",r<<16|g<<8|b);}',
    )

    blue = User.objects.filter(username="blue").first()
    Snippet.objects.create(
        title="b1",
        linenos=True,
        language="python",
        owner=blue,
        code=dedent(
            """
            operations = [
                migrations.RunPython(forward, reverse),
            ]
            """
        ),
    )


def reverse(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Snippet = apps.get_model("snippets", "Snippet")
    Snippet.objects.filter(title__in=["r1", "g1", "g2", "b1"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0002_create_users"),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
