name: Package CI

on: [push]

env:
  POETRY_VERSION: '1.2.2'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:
      - uses: actions/checkout@v3

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install

      - name: black
        run: poetry run black drf_vcr

      - name: isort
        run: poetry run isort drf_vcr

      - name: flake8
        run: poetry run flake8 drf_vcr

      - name: mypy
        run: poetry run mypy drf_vcr

      - name: pylint
        run: poetry run pylint drf_vcr

      - name: pytest
        run: poetry run pytest --random-order

