name: Test linting and run the test suit of sample_project

on: [push]


env:
  POETRY_VERSION: '1.2.2'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    defaults:
      run:
        working-directory: ./sample_project
    steps:
      - uses: actions/checkout@v3

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install

      - name: Print python versions
        run: |
          python -V
          poetry run python -V

      - name: Lint with flake8
        run: poetry run flake8
